export enum TypesOfSurgeryPreparations {
  VESTUARIO_DE_MUJER = 'WOMENS WARDROBE',
  VESTUARIO_DE_HOMBRES = 'MENS LOCKER ROOM',
  QUIRÓFANO = 'OPERTING ROOMS',
  SALAS_DE_RECUPERACIÓN = 'RECUPERATION ROOMS',
  TRANSFERENCIA_A_PISO = 'TRANSFER TO FLOOR',
  SALIDA = 'OUTPUT',
}
