export enum IdType {
  CÉDULA_DE_CIUDADANÍA = 'CC',
  CÉDULA_DE_EXTRANJERÍA = 'CE',
  TARJETA_DE_IDENTIDAD = 'TI',
  REGISTRO_CIVIL = 'RC',
  PASAPORTE = 'PP',
  PERMISO_ESPECIAL = 'PE',
  NÚMERO_IDENTIFICACIÓN_TRIBUTARIA = 'NIT',
  SALVOCONDUCTO = 'SC',
}
